name: test
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-23.10
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev
      - run: make MAINT=1
